ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1 = -(MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_2 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_4 = MDL_EE*MDL_COMPLEXI
      GC_14 = -(MDL_GW/MDL_SQRT__2)
      GC_15 = -((MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2)
      GC_16 = (MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_17 = MDL_GW/MDL_SQRT__2
      GC_18 = (MDL_CKM1X1*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_19 = (MDL_CKM1X2*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_21 = (MDL_CKM2X1*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_22 = (MDL_CKM2X2*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_24 = (MDL_CKM3X1*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_25 = (MDL_CKM3X2*MDL_COMPLEXI*MDL_GW)/MDL_SQRT__2
      GC_27 = (MDL_COMPLEXI*MDL_GW)/(2.000000D+00*MDL_CW)
      GC_28 = MDL_GW/MDL_CW
      GC_47 = -((MDL_CH*MDL_COMPLEXI*MDL_GWI)/MDL_SQRT__2)
      GC_48 = (MDL_CH*MDL_COMPLEXI*MDL_GWI)/MDL_SQRT__2
      GC_49 = (MDL_CW*MDL_COMPLEXI*MDL_GWI)/MDL_SQRT__2
      GC_89 = -((MDL_COMPLEXI*MDL_GWI*MDL_SH)/MDL_SQRT__2)
      GC_90 = (MDL_COMPLEXI*MDL_GWI*MDL_SH)/MDL_SQRT__2
      GC_96 = (MDL_CKM1X1*MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_97 = (MDL_CKM1X2*MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_99 = (MDL_CKM2X1*MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_100 = (MDL_CKM2X2*MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_104 = (MDL_EE*MDL_COMPLEXI*MDL_SW)/(3.000000D+00*MDL_CW)
      END
