ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of LHTkl'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_141 = ', GC_141
      WRITE(*,2) 'GC_206 = ', GC_206
      WRITE(*,2) 'GC_208 = ', GC_208
      WRITE(*,2) 'GC_209 = ', GC_209
      WRITE(*,2) 'GC_211 = ', GC_211
      WRITE(*,2) 'GC_212 = ', GC_212
      WRITE(*,2) 'GC_214 = ', GC_214
      WRITE(*,2) 'GC_215 = ', GC_215
      WRITE(*,2) 'GC_235 = ', GC_235
      WRITE(*,2) 'GC_236 = ', GC_236
      WRITE(*,2) 'GC_239 = ', GC_239
      WRITE(*,2) 'GC_242 = ', GC_242
      WRITE(*,2) 'GC_246 = ', GC_246
      WRITE(*,2) 'GC_250 = ', GC_250
      WRITE(*,2) 'GC_258 = ', GC_258
      WRITE(*,2) 'GC_262 = ', GC_262
      WRITE(*,2) 'GC_270 = ', GC_270
      WRITE(*,2) 'GC_274 = ', GC_274
