ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of LHTkl'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_141 = ', GC_141
      WRITE(*,2) 'GC_147 = ', GC_147
      WRITE(*,2) 'GC_196 = ', GC_196
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_198 = ', GC_198
      WRITE(*,2) 'GC_200 = ', GC_200
      WRITE(*,2) 'GC_201 = ', GC_201
      WRITE(*,2) 'GC_203 = ', GC_203
      WRITE(*,2) 'GC_204 = ', GC_204
      WRITE(*,2) 'GC_206 = ', GC_206
      WRITE(*,2) 'GC_208 = ', GC_208
      WRITE(*,2) 'GC_209 = ', GC_209
      WRITE(*,2) 'GC_211 = ', GC_211
      WRITE(*,2) 'GC_212 = ', GC_212
      WRITE(*,2) 'GC_214 = ', GC_214
      WRITE(*,2) 'GC_215 = ', GC_215
      WRITE(*,2) 'GC_235 = ', GC_235
      WRITE(*,2) 'GC_236 = ', GC_236
      WRITE(*,2) 'GC_239 = ', GC_239
      WRITE(*,2) 'GC_242 = ', GC_242
      WRITE(*,2) 'GC_245 = ', GC_245
      WRITE(*,2) 'GC_246 = ', GC_246
      WRITE(*,2) 'GC_249 = ', GC_249
      WRITE(*,2) 'GC_250 = ', GC_250
      WRITE(*,2) 'GC_257 = ', GC_257
      WRITE(*,2) 'GC_258 = ', GC_258
      WRITE(*,2) 'GC_261 = ', GC_261
      WRITE(*,2) 'GC_262 = ', GC_262
      WRITE(*,2) 'GC_269 = ', GC_269
      WRITE(*,2) 'GC_270 = ', GC_270
      WRITE(*,2) 'GC_273 = ', GC_273
      WRITE(*,2) 'GC_274 = ', GC_274
